---
- name: Setup Postgresql user
  postgresql_user: name={{ pg_user }}
                   password={{ DB_PASSWORD }}
                   role_attr_flags=NOCREATEDB,NOCREATEROLE,NOSUPERUSER

- name: Create project database
  postgresql_db: name={{ project_db }}
                 encoding="{{ database_encoding }}"
                 lc_collate="{{ database_lc_collate }}"
                 lc_ctype="{{ database_lc_ctype }}"
                 template="{{ database_template }}"
