---
- name: Setup Postgresql user
  postgresql_user: name={{ pg_user }} password={{ DB_PASSWORD }} role_attr_flags=CREATEDB,NOSUPERUSER

- name: Setup up Postgresql DB
  postgresql_db: name={{ project_db }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
